# Generated by Django 5.2.1 on 2025-06-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathersearch',
            options={'ordering': ['-searched_at']},
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='icon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='wind_speed',
            field=models.FloatField(default=0),
        ),
    ]
